wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1663150153.233506
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.13.1
      8:
      - 1
      - 5
alpha:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 75
beta:
  desc: null
  value: 3
epochs:
  desc: null
  value: 100
hidden_space_dimension:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
normalize_trials:
  desc: null
  value: 1
print_var:
  desc: null
  value: true
spectra_data_path:
  desc: null
  value: data/[2021-08-05_to_11-26]All_PlantSpectra.csv
time_interval_end:
  desc: null
  value: 360
time_interval_start:
  desc: null
  value: 45
training_type:
  desc: null
  value: double mnist water single level
water_data_path:
  desc: null
  value: data/[2021-08-05_to_11-26]PlantTest_Notes.csv
